[package]
name = "test-harness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
expect-test = "*"
escargot = "0.5"
command-error = "0.6"
utf8-command = "1"
